version: "3.4"
services:
    hnode_151_web:
        build: ./hnode_151_web
        image: 127.0.0.1:5000/hnode_151_web
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.default.rp_filter=0
            - net.ipv4.conf.all.rp_filter=0
        privileged: true
        networks:
            net_151_net0:
                ipv4_address: 10.151.0.71

        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "151"
            org.seedsecuritylabs.seedemu.meta.nodename: "web"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.151.0.71/24"

    rnode_151_router0:
        build: ./rnode_151_router0
        image: 127.0.0.1:5000/rnode_151_router0
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.default.rp_filter=0
            - net.ipv4.conf.all.rp_filter=0
        privileged: true
        networks:
            net_151_net0:
                ipv4_address: 10.151.0.254
            net_ix_ix100:
                ipv4_address: 10.100.0.151

        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "151"
            org.seedsecuritylabs.seedemu.meta.nodename: "router0"
            org.seedsecuritylabs.seedemu.meta.role: "Router"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.151.0.254/24"
            org.seedsecuritylabs.seedemu.meta.net.1.name: "ix100"
            org.seedsecuritylabs.seedemu.meta.net.1.address: "10.100.0.151/24"


networks:
    net_151_net0:
        driver_opts:
            com.docker.network.driver.mtu: 1500
        ipam:
            config:
                - subnet: 10.151.0.0/24
        labels:
            org.seedsecuritylabs.seedemu.meta.type: "local"
            org.seedsecuritylabs.seedemu.meta.scope: "151"
            org.seedsecuritylabs.seedemu.meta.name: "net0"
            org.seedsecuritylabs.seedemu.meta.prefix: "10.151.0.0/24"

    net_ix_ix100:
        external:
            name: sim_ix_net_ix_ix100
        driver: overlay
        labels:
            org.seedsecuritylabs.seedemu.meta.type: "global"
            org.seedsecuritylabs.seedemu.meta.scope: "ix"
            org.seedsecuritylabs.seedemu.meta.name: "ix100"
            org.seedsecuritylabs.seedemu.meta.prefix: "10.100.0.0/24"



